<?php

namespace Sandbox\CastingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DirectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectorRepository extends EntityRepository
{
}
